### ISSUE TITLE
Docs: `Json` type looks too small

### ISSUE THREAD

**Issue by ckiee** [jill64/ts-serde#94]
`interface` and `type` have weirdly different semantics with the `json` serde

:x: ` prefs.ts     6  21 error    2677   A type predicate's type must be assignable to its parameter's type.`
```ts
import { storage } from "@jill64/svelte-storage";
import { json } from "@jill64/svelte-storage/serde";

export const settings = storage("pupcat-settings", json<Settings>(
    // can validate here..
    (json): json is Settings => true
), {});

export interface Settings = {
    v: string;
    lwm: {
        expanded: boolean
    }
}
```

:white_check_mark:  `const settings: Writable<Settings>`
```diff
-export interface Settings = {
+export type Settings = {
```

This was hard to figure out: documenting it here in ts-serde and then linking that in the various leaf readmes (e.g. svelte-storage) would be lovely 💜

**Comment by jill64** [comment]
Thanks for opening this Issue!
I would like to add documentation based on your feedback.
